In [1]:
import numpy as np
A=np.array([[1,0,1],[1,2,3],[1,2,4]])
print('A=\n',A)
B=np.array([[3,1,4],[1,2,1],[3,1,1]])
print('B=\n',B)

A=
 [[1 0 1]
 [1 2 3]
 [1 2 4]]
B=
 [[3 1 4]
 [1 2 1]
 [3 1 1]]


In [2]:
#ALTERNATIVA A

det=np.linalg.det(A)
print('%.2f'% det)

2.00


In [4]:
#ALTERNATIVA B

inv=np.linalg.inv(B)
print(inv)

[[-0.06666667 -0.2         0.46666667]
 [-0.13333333  0.6        -0.06666667]
 [ 0.33333333 -0.         -0.33333333]]


In [5]:
#ALTERNATIVA C

a_transposta = A.T
print(a_transposta)
print(a_transposta.shape)

[[1 1 1]
 [0 2 2]
 [1 3 4]]
(3, 3)


In [7]:
#ALTERNATIVA D

D=np.dot(A,B)
print('D=\n',D)

D=
 [[ 6  2  5]
 [14  8  9]
 [17  9 10]]


In [10]:
#ALTERNATIVA E

E=A-4*B
print('E=\n',E)

E=
 [[-11  -4 -15]
 [ -3  -6  -1]
 [-11  -2   0]]
